# Robbing dev by FrahHS.
# Check documentation on the official website: https://robbingrp.gitbook.io/robbing/.
# Spigot page: https://www.spigotmc.org/resources/robbing-%E2%AD%95-custom-items-%E2%AD%90-robbery-rp-experience.105443/.
# If you need help or have any problem with the plugin join my discord: https://discord.gg/Hh9zMQnWvW.
#
# Have fun with Robbing :D

general:
  enabled: true
  # send on join message to operators if new version of the plugin will be available
  update_checker: true
  # You can contribute to the translation of the texts here: https://www.robbingrp.com/.
  language: "en"
  prefix: "§3[§6Robbing§3] §f"

database:
  # "SQLite" and "MySQL" supported, if you select MySQL you should have your own hosted database
  type: "SQLite"
  database_name: "RobbingDB"
  # Data in case of MySQL, not necessary if SQLite is selected
  mysql:
    address: "localhost"
    port: "3306"
    username: ""
    password: ""

rob:
  enabled: true
  # enable alert to send to the robbed target, write {thief} to use thief Display Name
  alert: true
  # down here list of all items not stealable,
  # only names, no id
  denied_items:
    - "DIAMOND"
    - "DIAMOND_BLOCK"
  whitelist_enabled: false
  whitelist_items:
    - "GOLD_INGOT"
  # max distance in block during robbing after that target inventory close
  max_distance: 5
  # cooldown setting (put timeout to 0 to disable)
  steal_cooldown: 120
  # sneaky right-click to steal if enabled, just right click if disabled
  sneak_to_rob: true
  # after a steal target will be blinded
  blindness_after_robbing: false
  # blindness duration in seconds (in enabled)
  blindness_duration: 5
  NPC_robbing: false
  # slowdown a thief shift left-clicking on him while he is robbing you.
  caught_robber:
    enabled: true
    can_jump: false
    slow_power: 5
    # how much time get slowed (in seconds)
    time: 20

handcuffing:
  enabled: true
  # enable right click handcuffed player to make he follow you
  following: true
  # put a cooldown to use handcuffs (in seconds)
  cooldown: 5
  enable_crafting: false
  # make possible escape from handcuffing
  #try_escape:
  #  enabled: false
  #  # delay handcuffing after clicking (in seconds).
  #  delayed_handcuffing: 2
  #  # min distance to escape handcuffing
  #  distance: 3
  # permitted commands while handcuffed
  permitted_commands:
    - login
    - register
lockpick:
  enable_crafting: false

# Emergency call
# when a player use /911 every other players with robbing.emergency.alert will receive a notification
emergencycall:
  enabled: true
  message: "{player} called 911 from {coordinates}, for: {reason}."
  # cooldown for /911 (in seconds), put 0 to disable
  cooldown: 10
